<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository{
	
	public function findByActivityWithUsername($id) {
		$qb = $this->createQueryBuilder('c');
		$qb				
			->leftJoin('c.activity', 'act')
			->addSelect('act')
			->leftJoin('c.user', 'user')
			->addSelect('user')
			->where('IDENTITY(c.activity) = '.$id)
		;
		return $qb->getQuery()->getResult();
	}
}
