<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetailReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailReservationRepository extends EntityRepository{
	
	public function findAllByPartner($id){
		
		$qb = $this->createQueryBuilder('a');
		$qb				
			->leftJoin('a.product', 'prod')
			->addSelect('prod')
			->leftJoin('prod.activity', 'act')
			->addSelect('act')
			->leftJoin('act.partner', 'part')
			->addSelect('part')
			->where('part.id = ' . $id)
			->leftJoin('a.reservation', 'res')
			->addSelect('res')
//			->leftJoin('res.user', 'user')
//			->addSelect('user')
			//->orderBy('res.date', 'DESC')
		;
		return $qb->getQuery()->getResult();
	}
	
}
