<?php

namespace AppBundle\Repository;

/**
 * DetailReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailReservationRepository extends \Doctrine\ORM\EntityRepository{
	
	public function findAllByPartner($id){
		
		$qb = $this->createQueryBuilder('a');
			$qb				
				->leftJoin('a.product', 'prod')
				->addSelect('prod')
				//->leftJoin('prod.activity', 'act')
				//->addSelect('act')
				//->innerJoin('act.partner', 'part', 'WITH', 'part.role=\'ROLE_PARTNER\'')
				//->addSelect('part')
				//->where('IDENTITY(part.id) = ' . $id)
				//->orderBy('a.recordingDate', 'DESC')
			;
			return $qb->getQuery()->getResult();
	}
}
