<?php

namespace AppBundle\Repository;

/**
 * DetailReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
