<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\User;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProductRepository extends EntityRepository{
	
	public function findNbTotProductByActivity($id, $reserved=false){
		
		$qb = $this->createQueryBuilder('p');
		$qb
			->select(COUNT(p))
			->where('IDENTITY(p.activity) = ' . $id)
			->innerJoin('p.activity', 'act', 'WITH', 'act.date > NOW()')
		;
		if($reserved){
			/*$qb
				->andWhere('')
			 * 
			 */
		}
		return $qb->getQuery()->getScalarResult();
	}
}
