<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository{
	
	
	public function findAllByPartner($id){
		
		$qb = $this->createQueryBuilder('u');
			$qb				
//				->where('IDENTITY(u.id) = ' . $id)
//				->Where('u.role=\'ROLE_PARTNER\'')
				->rightJoin('u.activities', 'act')
				->addSelect('act')
//				->leftJoin('act.product', 'prod')
//				->addSelect('prod')
//				->innerJoin('act.reservationDetails', 'res')
//				->addSelect('res')
				//->orderBy('a.recordingDate', 'DESC')
			;
		return $qb->getQuery()->getResult();
	}
}
