<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Hobby;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    //listing current User's hobbies
    public function findByUser(User $user) {
        $qb = $this->createQueryBuilder('h');
        
        $qb
            ->where('IDENTITY(h.user) = ' . $user->getId())
            ->orderBy('h.note', 'DESC')
        ;
        
        return $qb->getQuery()->getResult();
    }
    
}
