app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#ajouté par Florent pour le bundle easyAdmin
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

# FOSUserBundle 
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
partner:
    resource: "@AppBundle/Controller/Partner"
    type:     annotation
    prefix: /partner