app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#ajouté par Florent pour le bundle easyAdmin
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin