easy_admin:
    entities:
        Comment:
            class: AppBundle\Entity\Comment
            label: 'Comments'
            list:
                title: 'Comment %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'note', label: 'Rating' }
                    - { property: 'user', label: 'User name' }
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'date', label: 'Comment date' }
            show:
                fields:
                    - 'id'
                    - { property: 'comment', label: 'Comment' }
                    - { property: 'user', label: 'User name' }
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'note', label: 'Rating' }
                    - { property: 'date', label: 'Comment date' }