easy_admin:
    entities:
        Photo:
            class: AppBundle\Entity\Photo
            label: 'Photo'
            list:
                title: 'Photo %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'name', label: 'Path and name file' }
            show:
                fields:
                    - 'id'
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'name', label: 'Path and name file' }
         