easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Product'
            list:
                title: 'Product %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'date', label: 'Activity date' }
                    - { property: 'price', label: 'Price' }
                    - { property: 'stock', label: 'Stock' }
            show:
                fields:
                    - 'id'
                    - { property: 'activity', label: 'Activity' }
                    - { property: 'date', label: 'Activity date' }
                    - { property: 'price', label: 'Price' }
                    - { property: 'stock', label: 'Stock' }