easy_admin:
    entities:
        DetailReservation:
            class: AppBundle\Entity\DetailReservation
            label: 'Reservation details'
            list:
                title: 'Reservation detail %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'quantity', label: 'Quantity' }
                    - { property: 'reservation', label: 'Reservation' }
            show:
                fields:
                    - 'id'
                    - { property: 'quantity', label: 'Quantity' }
                    - { property: 'reservation', label: 'Reservation' }
